### ISSUE TITLE
What is breakpoint graph?

### ISSUE THREAD

**Issue by techtonik** [aganezov/bg#1]

**Comment by techtonik** [comment]
@aganezov and still - what is it?

**Comment by aganezov** [comment]
Breakpoint is a data structure often used in the area of comparative genomics and genome rearrangement analysis. You can learn more about the area, the data structure, and research that is being done using it in the following publications:

* [Transforming men into mice (polynomial algorithm for genomic distance problem) (pdf)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.50.5495&rep=rep1&type=pdf)
* [Transforming cabbage into turnip: polynomial algorithm for sorting signed permutations by reversals (pdf)](http://webdocs.cs.ualberta.ca/~ghlin/CMPUT606/Papers/sbrHP99.pdf)
* [Genome Rearrangements in Mammalian Evolution: Lessons From Human and Mouse Genomes](http://genome.cshlp.org/content/13/1/37.long)
* [Whole genome duplications, multi-break rearrangements, and genome halving problem (pdf)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.89.2657&rep=rep1&type=pdf)
* [Scaffold assembly based on genome rearrangement analysis (pdf)](https://pdfs.semanticscholar.org/3568/dbe766e45c31e689f6365c35237198fe61d1.pdf)
* [Multi-break rearrangements and chromosomal evolution](http://www.sciencedirect.com/science/article/pii/S0304397508000352)
* etc

You can also used [google scholar](https://scholar.google.com/scholar?hl=en&q=breakpoint+graph) to see more broadly where this data structure is utilized.
